apiVersion: v1
kind: Service
metadata:
    name: edgems
    namespace: acubed
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: edgems
---
apiVersion : apps/v1beta1
kind: Deployment
metadata:
    name: edgems 
    namespace: acubed
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: edgems 
    spec:
      containers:
        - name: edgems 
          image: acubedcr.azurecr.io/edgems:buddy
          imagePullPolicy: Always
          ports:
          - containerPort: 80
      imagePullSecrets: 
          - name: 'acubedcr8786ba3e-auth'
